export const GET_COINS_REQUEST = "GET_COINS_REQUEST";
export const GET_COINS_FAILURE = "GET_COINS_FAILURE";
export const GET_COINS_SUCCESS = "GET_COINS_SUCCESS";

export const GET_SINGLE_COIN_SUCCESS = "GET_SINGLE_COIN_SUCCESS";